/**
 * @fileOverview Handles stripping common prefixes from search queries.
 */

const prefixes: string[] = [
    "what is",
    "what is this",
    "what is that",
    "what is meant by",
    "what is the meaning of",
    "meaning of",
    "meaning",
    "define",
    "definition of",
    "give me the definition of",
    "can you define",
    "can u define",
    "definition pls",
    "definition plz",
    "tell me the definition of",
    "explain",
    "explain this",
    "explain about",
    "explain the meaning of",
    "explain to me",
    "pls explain",
    "plz explain",
    "can you explain",
    "can u explain",
    "elaborate",
    "elaborate on",
    "clarify",
    "clarify this",
    "clarify the meaning of",
    "tell me about",
    "tell me something about",
    "tell me details about",
    "tell me more about",
    "tell something about",
    "tell me all about",
    "tell me little about",
    "say something about",
    "say more about",
    "say little about",
    "say all about",
    "who is",
    "who was",
    "who are",
    "whos",
    "who’s",
    "do you know who",
    "do u know who",
    "tell me who is",
    "tell me who was",
    "tell me about who",
    "what do you know about",
    "what do u know about",
    "do you know about",
    "do u know about",
    "do you know",
    "do u know",
    "know about",
    "know",
    "what do you mean by",
    "what do u mean by",
    "what is called",
    "what is known as",
    "what’s called",
    "what’s known as",
    "what’s meant by",
    "what’s the definition of",
    "what’s the meaning of",
    "give me info about",
    "give info about",
    "give me some info on",
    "give some info about",
    "give me information about",
    "give information about",
    "give me details about",
    "give details about",
    "give me knowledge on",
    "give knowledge about",
    "tell me the meaning of",
    "tell me the definition of",
    "tell me the explanation of",
    "tell me info about",
    "tell me in detail about",
    "tell me in short about",
    "give me a short note on",
    "give me a note on",
    "short note on",
    "note on",
    "what is the purpose of",
    "purpose of",
    "use of",
    "uses of",
    "utility of",
    "function of",
    "role of",
    "what does … mean",
    "what does it mean",
    "what do you mean",
    "what u mean",
    "what is meant",
    "what is it",
    "what is it about",
    "what’s this",
    "what’s that",
    "what’s",
    "what’s all about",
    "what’s the concept of",
    "concept of",
    "idea of",
    "basic idea of",
    "what is concept of",
    "define in simple words",
    "meaning in simple words",
    "explain in simple terms",
    "explain simply",
    "explain simply what is",
    "explain it simply",
    "give me simple explanation",
    "give me easy meaning",
    "give me simple meaning",
    "what’s the easy meaning of",
    "what’s the simple meaning of",
    "in simple words",
    "in easy words",
    "easy explanation of",
    "basic explanation of",
    "tell me briefly about",
    "tell me briefly",
    "briefly explain",
    "brief note on",
    "short explanation of",
    "short description of",
    "describe",
    "description of",
    "give description of",
    "what is description of",
    "what’s description of",
    "explain description of",
    "what is called as",
    "what is referred to as",
    "what’s referred to as",
    "what’s called as",
    "referred to as",
    "referred as",
    "what’s the meaning behind",
    "meaning behind",
    "significance of",
    "importance of",
    "why is … important",
    "why is … used",
    "why do we use",
    "why is … called",
    "reason of",
    "reason for",
    "origin of",
    "history of",
    "story of",
    "explain history of",
    "who invented",
    "who created",
    "who discovered",
    "discovery of",
    "invention of",
    "creator of",
    "founder of",
    "father of",
    "mother of",
    "what stands for",
    "what does … stand for",
    "stands for",
    "full form of",
    "what’s the full form of",
    "what’s … full form",
    "give me full form of",
    "short form of",
    "abbreviation of",
    "what’s abbreviation of",
    "expand",
    "expansion of",
    "expansion pls",
    "expansion plz",
    "what does abbreviation … mean",
    "explain abbreviation",
    "what’s acronym of",
    "acronym of",
    "meaning of acronym",
    "expand acronym"
].sort((a, b) => b.length - a.length); // Sort by length descending to match longest prefixes first


/**
 * Strips a known prefix from the beginning of a query string.
 * @param query The user's input query.
 * @returns The query with the prefix removed, or null if no prefix was found.
 */
export function stripQueryPrefix(query: string): string | null {
    const normalizedQuery = query.toLowerCase().trim();
    for (const prefix of prefixes) {
      // Check if the query starts with the prefix, ensuring it's a whole word.
      // The " is..." handles cases where the prefix is "is" but the query is "island".
      if (normalizedQuery.startsWith(prefix + ' ') || normalizedQuery.startsWith(prefix + '?') || normalizedQuery === prefix) {
        const stripped = query.substring(prefix.length).trim();
        // Remove trailing question marks if they exist
        if (stripped.endsWith('?')) {
            return stripped.slice(0, -1).trim();
        }
        return stripped;
      }
    }
    return null;
}
  
